//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Yuehkap5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о закупках.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОЗакупках CustomAttributes)

    // *** End programmer edit section *** (ОтчетОЗакупках CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о закупках")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОЗакупкахE", new string[0])]
    [View("ОтчетОЗакупкахL", new string[0])]
    public class ОтчетОЗакупках : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (ОтчетОЗакупках CustomMembers)

        // *** End programmer edit section *** (ОтчетОЗакупках CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОЗакупкахE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахE", typeof(IIS.Yuehkap5.ОтчетОЗакупках));
                }
            }
            
            /// <summary>
            /// "ОтчетОЗакупкахL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахL", typeof(IIS.Yuehkap5.ОтчетОЗакупках));
                }
            }
        }
    }
}
