//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Yuehkap5
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние поставок.
    /// </summary>
    // *** Start programmer edit section *** (СостОплаты CustomAttributes)

    // *** End programmer edit section *** (СостОплаты CustomAttributes)
    public enum СостОплаты
    {
        
        // *** Start programmer edit section *** (СостОплаты.ПолностьюОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.ПолностьюОтгружен CustomAttributes)
        ПолностьюОтгружен,
        
        // *** Start programmer edit section *** (СостОплаты.ЧастичноОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.ЧастичноОтгружен CustomAttributes)
        ЧастичноОтгружен,
        
        // *** Start programmer edit section *** (СостОплаты.НеОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.НеОтгружен CustomAttributes)
        НеОтгружен,
    }
}
